# Generated by Django 4.2.7 on 2023-12-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
    ]
