# Generated by Django 4.2.7 on 2023-12-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20231203_1828'),
    ]

    operations = [
    ]
