# Generated by Django 4.2.7 on 2023-12-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_auto_20231203_1905'),
    ]

    operations = [
    ]
