# Generated by Django 4.2.7 on 2023-12-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
